# Generated by Django 5.1.1 on 2025-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
