# Generated by Django 5.1.1 on 2025-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userorder_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
