# Generated by Django 5.1.1 on 2025-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userdeliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeliveryaddress',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
