# Generated by Django 5.1.1 on 2025-02-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userorder_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
