# Generated by Django 5.1.1 on 2025-03-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sellerorder_order_consignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorder',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='sellerorder',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='sellerorder',
            name='order_consignee',
        ),
        migrations.RemoveField(
            model_name='sellerorder',
            name='order_total',
        ),
        migrations.AddField(
            model_name='sellerorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userorder'),
        ),
    ]
