# Generated by Django 5.1.1 on 2025-03-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_sellerorder_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorder',
            name='order_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
