# Generated by Django 5.1.1 on 2025-07-16 04:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sellerorder_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('variant_image', models.ImageField(blank=True, null=True, upload_to='product_variants', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='api.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'variant_name'), name='unique_variant_per_product')],
            },
        ),
    ]
