# Generated by Django 5.1.1 on 2025-07-30 05:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_image', models.ImageField(blank=True, null=True, upload_to='product_variants', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='api.productvariant')),
            ],
        ),
    ]
