# Generated by Django 5.1.1 on 2025-07-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_productvariant_variant_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
