# Generated by Django 5.1.1 on 2025-08-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
