# Generated by Django 5.1.1 on 2025-08-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_product_product_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
