# Generated by Django 5.1.1 on 2025-08-14 04:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])])),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='variantimage',
            name='variant',
        ),
        migrations.RemoveConstraint(
            model_name='productvariant',
            name='unique_variant_per_product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_base_price',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='api.product'),
        ),
        migrations.AddField(
            model_name='productvariantcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_categories', to='api.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.productvariantcategory'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('variant_category', 'variant_name'), name='unique_variant_per_category'),
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
