# Generated by Django 5.1.1 on 2025-08-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_productimage_productvariantcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='variant_price',
            new_name='extra_price',
        ),
    ]
