# Generated by Django 5.1.1 on 2025-08-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_cartitem_unique_together_cartitem_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorderitem',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userorderitem',
            name='product_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userorderitem',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userorderitem',
            name='unit_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userorderitem',
            name='variant_name',
            field=models.CharField(max_length=50),
        ),
    ]
