# Generated by Django 5.1.1 on 2025-08-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_userorderitem_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderitem',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='userorderitem',
            name='variant_name',
        ),
        migrations.CreateModel(
            name='UserOrderItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=50)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_variants', to='api.userorderitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productvariant')),
                ('variant_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productvariantcategory')),
            ],
        ),
    ]
