# Generated by Django 5.1.1 on 2025-09-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_searchlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
