# Generated by Django 5.1.1 on 2025-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerstore',
            name='store_category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion & Clothing'), ('beauty', 'Beauty & Personal Care'), ('home', 'Home & Kitchen'), ('sports   ', 'Sports & Outdoors'), ('books', 'Books & Stationery'), ('health', 'Health & Wellness'), ('toys', 'Toys & Games'), ('automotive', 'Automotive'), ('jewelry', 'Jewelry & Accessories'), ('grocery', 'Grocery & Food'), ('baby', 'Baby Products'), ('furniture', 'Furniture & Decor'), ('pet', 'Pet Supplies'), ('office', 'Office Supplies')], max_length=50, null=True),
        ),
    ]
